name: Release - Tag and publish Docker image

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version (ie 5.5.0)'
        required: true

jobs:
  create_release: 
    name: Publish Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Repository name to lowercase
        id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}:${{inputs.versionName}}
          push: true
